### ISSUE TITLE
Windows and other plateform support

### ISSUE THREAD

**Issue by awdDev786** [mklement0/ttab#11]
I need such functionality  in my windows environment.but this isnt supporting windows or linux.giving error in installation as 

     Unsupported platform for ttab@0.6.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

Is there any plan to add it or not?

**Comment by mklement0** [comment]
Unfortunately, I have no plans to add support for other platforms. 

This would be a significant amount of work, and especially tricky on Linux platforms, where many different terminal programs exist  - see #5.

**Comment by lalilaloe** [comment]
I creatief a small package tot accommodate for Windows Terminal. The api of wt.exe is still under development but you can check if out at: [https://github.com/lalilaloe/wttab](https://github.com/lalilaloe/wttab)

**Comment by mklement0** [comment]
That's neat, @lalilaloe - I've updated the README to point to your project.

I noticed that your README states "Linux" with respect to `ttab`, but please note that it was primarily created for *macOS*, where it offers the most functionality; Linux support - for the GNOME terminal only - came later, and has limitations.
