### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by amissine** [mklement0/ttab#12]
Dear Mr. Klement,

Thank you very much for the **ttab** utility! It is an exceptional piece of work both implementation- and design-wise. In fact, I have just forked the whole project with the intent of using it as a template for my next one, **lint**. The **lint** project will be solely my own responsibility, but I must and very much willing to give full credit to the project of yours I am basing it on. And I am not sure how to properly reflect it in the LICENSE.md file. Please let me know if the following line will be satisfactory:

Copyright (c) 2017 Alec Missine alec_missine@yahoo.com, released under the MIT license. Based off of [ttab](https://github.com/mklement0/ttab).

Thank you,
Alec

**Comment by mklement0** [comment]
Hi,

Thank you for kind words. I'm glad you find my project useful and plan on building on it.
What, specifically, will lint be?

I'm OK with the license text you propose.

Best,

Michael

**Comment by amissine** [comment]
Hi Michael,

Thank you for your prompt response! To start off, I misspelled the name of my project in the message, and it is **lnet**, stands for Localized Network. 

My home computer is shielded from the Internet by a router, and to give external access to it I can either configure port forwarding on the router, or use SSH remote port forwarding on my computer. In the latter case, I make SSH connection to a box that is visible (e.g., it's router has been preconfigured to make it visible from the Internet) and set the remote port forwarding option on that connection. When this connection gets established, a terminal window pops up on that box, with an SSH session from that box to my computer. If that box runs Mac OS X, **ttab** will be used.

Cheers,
Alec

**Comment by mklement0** [comment]
Sounds cool, thanks for letting me know.
