### ISSUE TITLE
-g and -G flags still focus the new tab?

### ISSUE THREAD

**Issue by dgolant** [mklement0/ttab#13]
Hi, I just started using ttab and it looks like when I pass in `ttab -G -t 'Datastore Emulator' gcloud beta emulators datastore start`, the new tab still receives focus. I've attached a gif, to clarify

![200w_d](https://user-images.githubusercontent.com/8434515/32256973-bd77aed2-be88-11e7-9a61-74daa5bf0322.gif)

it may be a little easier to follow [here](https://giphy.com/gifs/ttab-26vaxA2ZEFO4UqVEY/download)

**Comment by mklement0** [comment]
Thanks for letting me know. I'll take a look.

**Comment by robotdana** [comment]
I noticed this after updating to High Sierra

**Comment by mklement0** [comment]
I've just published v0.6.1, which should fix the problem.

The reason it broke is that Apple changed Terminal.app's scripting object model with respect to tabs.

**Comment by robotdana** [comment]
Thanks so much :)

**Comment by LoganBresnahan** [comment]
I believe this is an issue again. Using the Terminal application, `-G` does not stop the new tab from coming into focus for me.
Terminal Version, 2.11 (440)

**Comment by mklement0** [comment]
Thanks for letting me know, @LoganBresnahan - it seems to be a problem only in `Terminal.app`, not `iTerm2.app` - the problem is specific to the `Terminal.app` version that comes with Big Sur - things work fine on Catalina.

I'll take a look.

**Comment by LoganBresnahan** [comment]
> Thanks for letting me know, @LoganBresnahan - it seems to be a problem only in `Terminal.app`, not `iTerm2.app` - the problem is specific to the `Terminal.app` version that comes with Big Sur - things work fine on Catalina.
> 
> I'll take a look.

Thanks a lot for taking a look, and thanks so much for your work on ttab! I really appreciate it :+1:

**Comment by mklement0** [comment]
This should be fixed in the just-released v0.7.1, @LoganBresnahan; and thanks for the nice feedback.
