### ISSUE TITLE
Throw Incompatible OS Error Only on Use Rather than On Install

### ISSUE THREAD

**Issue by philippefutureboy** [mklement0/ttab#14]
Greetings!

I use `ttab` for development purposes on my macOS machine. I've noticed that when pushing my node js build for production on a node:carbon (linux) docker image, `ttab` causes the build to fail because `[the] platform "linux" is incompatible with this module`. Would it be possible to throw this error only when used rather than when installed ( or to support Linux #5 )?

Cheers ✨

**Comment by mklement0** [comment]
If you've correctly declared `ttab` as a development-only dependency (key `devDependencies`) in your `package.json` file, then setting `NODE_ENV` to `production` or installing with `npm install --only=production` may help - see https://stackoverflow.com/a/9276112/45375

**Comment by mklement0** [comment]
I'll close this for now, but we can revisit if my suggestion didn't help.

**Comment by philippefutureboy** [comment]
Confirmed to work with `yarn install --production`! Thanks for the tip :)
