### ISSUE TITLE
Issue when run after tab is closed

### ISSUE THREAD

**Issue by stygiansabyss** [mklement0/ttab#16]
I was trying to make a script that opens a tab and runs a command for the user using exec.  It works fine right after iterm2 is launched.  However, once the tab is closed (when the command ends) and I run ttab again, it just hangs forever.  I don't see anything in ps aux that would be killable as a hung up task so I'm at a loss on what it could be.

```bash
travisb at traviss-mbp in ~   × @12:19
> ttab -w exec sudo lsyncd /Users/travisb/Code/local/ims_v3/sync.lua
travisb at traviss-mbp in ~    @12:20
> ttab exec sudo lsyncd /Users/travisb/Code/local/ims_v3/sync.lua
^C
travisb at traviss-mbp in ~   × @12:22
```

**Comment by mklement0** [comment]
Curious; without more information, I'm afraid I can't help.

Can you reproduce this with a standard utility?

Have you tried upgrading iTerm2?

**Comment by mklement0** [comment]
I'm closing this for now, but if you come up with a reproducible case, I'm happy to revisit.
