### ISSUE TITLE
ttab should not switch current application to "Terminal" if it is run in the background

### ISSUE THREAD

**Issue by gpanganiban** [mklement0/ttab#17]
- Install ttab
- Enter this script in Terminal: 
`sleep 10; ttab -G top &`
- Immediatly switch to a different app 
- wait 10 seconds

While using different app, The ttab process will briefly steal focus and become the frontmost terminal for a moment then return to the other app.

**Comment by mklement0** [comment]
@gpanganiban: Sorry it took me so long to respond.

While I fully agree that `ttab` _shouldn't_ do that, it is currently unavoidable for technical reasons; from `man ttab`:


> NOTE: With `-g` or `-G` specified, for technical reasons, Terminal/iTerm2 /
the new tab will still activate briefly, temporarily in most scenarios.

I haven't looked in a while, but if you know of a technical solution that avoids the problem, let me know.
