### ISSUE TITLE
ttab consistently opens new windows instead of tabs

### ISSUE THREAD

**Issue by atomless** [mklement0/ttab#2]
When stringing a chain of commands together ttab consistently opens new windows instead of tabs, any idea why this would happen?

For example: 
```
ttb -t 'title1' <some cmd> && ttab -t 'title2' <some cmd> && sleep 5 && ttab -t 'title3' <some cmd>
```

The title3 tab will be opened in a new terminal window rather than a tab.

**Comment by mklement0** [comment]
Curios. On my OS X 10.11.4 machine, when I run

     ttab -t 'title1' date  && ttab -t 'title2' date  && sleep 5 && ttab -t 'title3' date

all tabs open in the _current_ window.

What OS X version are you on?

**Comment by mklement0** [comment]
I'll close this for now, but if you want me to look at a specific command that exhibits the symptom, I'm happy to revisit.
