### ISSUE TITLE
Doesn't work with latest iTerm2

### ISSUE THREAD

**Issue by rblalock** [mklement0/ttab#21]
The tabs open but doesn't run thecommand

**Comment by mklement0** [comment]
@rblalock: 

I just tried with the current stable version, 3.3.4, and I don't see a problem; the following work fine for me:

```sh
ttab ls  # open new tab and run `ls`
ttab -w ls # open new window and run `ls`
```

What version are you using? A test release? Are you aware of upcoming breaking changes to the AppleScript API?

**Comment by rblalock** [comment]
Sorry, I just tried again.  It doesn't work with the latest beta...so that's the issue.  Hopefully it's something they just broke on their side, with apple script.

**Comment by mklement0** [comment]
Thanks for following up. I sure hope that they won't break the AppleScript API, but do let me know if you hear anything.
