### ISSUE TITLE
How to Close the Opened tab or Window?

### ISSUE THREAD

**Issue by wahello** [mklement0/ttab#22]
It will get closer to perfect if ttab has function to close the opened tab/window.

**Comment by mklement0** [comment]
@wahello: `exit` normally not just exits the process, but also closes the window / tab.

Are you thinking of scenarios where exiting the process (shell) _doesn't_ close the window / tab?

If so, can you elaborate?

**Comment by mklement0** [comment]
In case you meant instructing `ttab` to automatically close the new tab after a given command has finished:

For a _single_ command, prepend `exec`; e.g.:

```sh
ttab -t 'Will close when find finishes' exec find $HOME
```

For a multi-command command line; append `; exit`; e.g.:

```sh
ttab -t 'Will close when you press a key once finished' 'find $HOME; echo Press a key to exit.; read -rsn 1; exit'
```
