### ISSUE TITLE
Create Homebrew tap

### ISSUE THREAD

**Issue by singingwolfboy** [mklement0/ttab#24]
Thanks for this project, @mklement0! However, I find it a bit annoying that I have to use npm to install it, when it's just a simple bash script. Have you considered putting it into [Homebrew](https://brew.sh/), as well?

[I made a pull request to add this project to Homebrew](https://github.com/Homebrew/homebrew-core/pull/48118), but one of the maintainers suggested that this project isn't popular/notable enough to put in the core tap. However, [anyone can create their own tap](https://docs.brew.sh/Taps), and I feel like it makes the most sense for the tap for this project to be on your GitHub account, if you're OK with that.

Would you like to create a Homebrew tap, copy my formula file into it, and mention it on the README for this project?

**Comment by mklement0** [comment]
Good idea, @singingwolfboy.

Bummer that they won't accept it into homebrew-core.

I've added a simplified version of your formula and updated the read-me: please see https://github.com/mklement0/ttab#installation-via-homebrew

Note that a custom tap would really only make sense for a repo with _multiple_ formulae, so the instructions simply use the raw URL to the `*.rb` file.

Thanks!
