### ISSUE TITLE
Feature Suggestion: Config file

### ISSUE THREAD

**Issue by tbrodbeck** [mklement0/ttab#28]
Would be great if you could define your preferences (like iTerm2) in a config file if one exists. For example `~/.ttabrc`

**Comment by mklement0** [comment]
Which preferences (options), specifically, do you see as useful for presetting via such a file?

**Comment by mklement0** [comment]
@tbrodbeck, I'm closing this for now due to lack of feedback, but I'm happy to discuss the rationale with further input.
