### ISSUE TITLE
Support iTerm

### ISSUE THREAD

**Issue by ro31337** [mklement0/ttab#3]
iTerm is quite popular among devs who work on OS X.  But `ttab` gives you error:

> 79:307: execution error: System Events got an error: Can’t get application process "Terminal". (-1728)

It would be great if iTerm can be supported.

**Comment by mklement0** [comment]
I've just released v0.3.0 with iTerm support.

It is experimental in that the automated tests only cover Terminal.app for now.

Note that `-t` for setting the title isn't supported (if you know how to make that work, do let me know).

Let me know how it goes.
