### ISSUE TITLE
feature: Support for tmux

### ISSUE THREAD

**Issue by tjmgregory** [mklement0/ttab#36]
Would love for this to support [tmux](https://github.com/tmux/tmux/wiki), which currently I use with Alacritty. Happy to be assigned this, to act as a reminder for me to get this done.

**Comment by tjmgregory** [comment]
It appears I missed your reply, apologies! Tmux is a terminal multiplexer (allows you to have multiple panes in one window) and ultimately it would be super if this could open up multiple panes in `tmux`, much like windows/tabs in iTerm :)

**Comment by Nauxscript** [comment]
I have the same qutions，would you support some other terminal application like [Warp](https://www.warp.dev/)?

**Comment by mklement0** [comment]
@Nauxscript, can you please open a _new_ issue, specifically for Warp? 

If you can, please add information about its CLI, which will give me a sense of whether adding support is worth contemplating.

**Comment by mklement0** [comment]
@tjmgregory, I missed the [Alacritty](https://alacritty.org/) angle:

I'm assuming you are looking for a `ttab tmux ...` command to open in another _Alacritty_ tab, right?

That would require adding support for Alacritty, and, similarly, a look at its CLI would be required to assess the potential for adding support.

**Comment by tjmgregory** [comment]
Hiya @mklement0 - thanks for getting back to me. That's right. The use case we had at work was we had `ttab` used in some of our system setup scripts, which I wouldn't have an easy time of changing to support Alacritty 👍 Don't feel an urgency to add on my behalf now though, as the infra team moved our setup to use [Tilt](https://tilt.dev/) so little gets spun up on our local machines these days. But thanks awesomely for getting back to me 🦸
