### ISSUE TITLE
Fluent terminal integration

### ISSUE THREAD

**Issue by utiq** [mklement0/ttab#38]
Do you have plans to make this work with https://github.com/felixse/FluentTerminal?

**Comment by mklement0** [comment]
Thanks for the suggestion, @utiq, but `ttab` is implemented as a `bash` shell script, so it won't work natively on Windows.

Perhaps you can ask the maintainers of the Windows-focused https://github.com/lalilaloe/wttab project.

**Comment by utiq** [comment]
I'm using [WSL 2](https://docs.microsoft.com/en-us/windows/wsl/about) running an Ubuntu 20.04, still not possible?

**Comment by mklement0** [comment]
It's possible (but would obviously be limited to an optional `bash` environment, such as WSL), but would require building  on FluentTerminal's own CLI, which at least at the moment seems quite limited: https://github.com/felixse/FluentTerminal/wiki/Command-Line-Arguments

I using this CLI directly not an option for you?

Or are you looking to use `ttab` as a unified utility across multiple platforms and terminal emulators?
