### ISSUE TITLE
The platform "win32" is incompatible with this module.

### ISSUE THREAD

**Issue by NaveenkumarMD** [mklement0/ttab#46]
Platform: Windows 11
node version:16

Error:
![image](https://user-images.githubusercontent.com/72449129/190562007-92b12957-073a-457a-8df9-9bdf8902615b.png)

System configuration:
![image](https://user-images.githubusercontent.com/72449129/190562120-1fe7db8b-dd29-4319-b31f-f00b8cda2b02.png)

**Comment by mklement0** [comment]
This is the standard error message telling you that your platform - Windows - is incompatible with `ttab`.

`ttab` is supported only on macOS and Linux, and only with specific terminal emulators.

To quote from the read-me file:

> * Note: `ttab` does _not_ support **Windows**; consider using the [Windows Terminal](https://github.com/microsoft/terminal/blob/main/README.md)-based [`wttab`](https://github.com/lalilaloe/wttab) utility there.
