### ISSUE TITLE
Not working in macOS Ventura

### ISSUE THREAD

**Issue by stx** [mklement0/ttab#47]
Quite frequently, in the macOS Ventura beta, `ttab <command>` will result in the command being run in the current window, and a new, empty tab being opened. Happens about half the time.

**Comment by mklement0** [comment]
Sorry to hear it. Is this in Terminal.app or iTerm2.app, or both?

**Comment by stx** [comment]
> Sorry to hear it. Is this in Terminal.app or iTerm2.app, or both?

Terminal.app

**Comment by mklement0** [comment]
I don't have the beta, so I can't look into this. If you have further info to share, please do. Generally, note that AppleScript, which `ttab` relies on, is getting less and less love as time goes on.

**Comment by JamesCouncilTN** [comment]
I am experiencing the issue only when I attempt to apply a profile with my window (i.e. -s Homebrew).  When I attempt to do that, it will open a new window in that profile, but return to the current window and perform the command.  This worked flawlessly until I just updated my Mac to Ventura.

I love the tool by the way.

**Comment by JamesCouncilTN** [comment]
I just verified, thanks to your comments above, that iTerm2 does not suffer from the problem that I am facing in Terminal.

**Comment by mklement0** [comment]
Thanks for the nice feedback, @JamesCouncilTN.

I have Ventura now and do see the problem, and only in Terminal.app, as you state:

To elaborate on @stx' finding, it seems that the various options (`-t`, working dir, startup command) are applied to the _calling_ tab, not the newly created one.

Very odd. I do hope that they didn't break AppleScript support fundamentally; I have yet to take a closer look.

**Comment by benmatselby** [comment]
Hey folks. Just to drop a note to say that since I upgraded to `13.1 (22C65)` it's consistently been working for me again. 😅

**Comment by mklement0** [comment]
That's great news, thanks for sharing.

I can confirm that it's working again for me too.

I hope that goes for you too, @stx and @JamesCouncilTN.
