### ISSUE TITLE
Terminal bootstrap interrupt ttab command

### ISSUE THREAD

**Issue by Avivbens** [mklement0/ttab#58]
On executing commands via `ttab`, there are times that the Terminal bootstrap cancels the execution of `ttab`, because it's been inserted before the bootstrap:

![CleanShot 2023-01-11 at 10 16 49@2x](https://user-images.githubusercontent.com/77183871/211753831-efe45270-42c6-4c3d-b389-219e88d4fe8c.png)

**Comment by mklement0** [comment]
What is Terminal bootstrap. Are you referring to a hooking mechanism for Terminal.app?

Note that `ttab` simply delegates the command execution in the new tab to Terminal.app's `do script` command, and that command has no parameters with respect to timing.

**Comment by Avivbens** [comment]
I mean that the terminal loads all configurations from `~/.zshrc`, which can cause a delay 
The command from `ttab` often getting executed before that bootstrap

**Comment by mklement0** [comment]
I see. When I provoke the symptom, I see a _display_ problem:

The command is printed _twice_:
 * first intermingled with output from the profile / initialization file, if any
 * then again, after the profile / initialization file has loaded -  when it is - successfully - executed.

Are you seeing _more_ than a display problem?

**Comment by Avivbens** [comment]
Yeah, but it's not about printing it twice, I don't care if it does. 
Problem is that there is a chance the command won't get executed 😥️

**Comment by mklement0** [comment]
How long does processing of ~/.zshrc typically take in your case?

When it fails, what, specifically, happens / doesn't happen?

The best thing that could be done is to introduce a _fixed delay_ before `ttab` sends the command,
perhaps configurable via an environment variable.

Since you're the first one to report this problem, I'm assuming that it is rare, so I'm hesitant to put in a _default_ delay.

**Comment by Avivbens** [comment]
The shell bootstrap could take 0.5-7.5 seconds, depending on the machine warn up. In most cases, it's like 0.7. 

Once it fails, it simply prints the command before the bootstrap and that's it. 


I think the best solution will be that delay via a flag, with a default of no delay.

**Comment by Avivbens** [comment]
Let's put it in ms format, so it'll be easier to config and determine the exact time 🙂

**Comment by mklement0** [comment]
v08.0 was just published (also to the npm registry).

`-l <secs>` specifies a delay, and the value can be fractional (e.g. `-l 0.8`)

I put in a small default delay (`0.1`) to lessen the risk of running in the problem you saw.

You may preset the default via environment variable `TTAB_CMD_DELAY`

One caveat is that the delay affects how long a tab is temporarily activated when using the `-g` / `-G` options.

---

As an aside:

The Homebrew installation is still cumbersome, and I wonder if `ttab` is now "notable" enough to warrant inclusion as a core Homebrew formula.

See #49, if you're so inclined (the OP there asks for a _tap_, which I haven't looked into yet, but inclusion as a core formula is obviously preferable).

**Comment by Avivbens** [comment]
Works like a charm ✨️

**Comment by mklement0** [comment]
Glad to hear it, @Avivbens.
