### ISSUE TITLE
Add method to navigate between splits (iTerm2)

### ISSUE THREAD

**Issue by danielcompton** [mklement0/ttab#75]
I like to have a 3x2 grid of tabs when working, with each one having a different program running. I haven't been able to work out how to reproduce this in ttab because I need to move between the split to be able to create new splits in the right places:

<img width="400" alt="Screenshot of iTerm2 at 30 Aug 2024 at 10_14_00 AM" src="https://github.com/user-attachments/assets/d444adc7-6ca0-4b1f-88db-fe8d06fe06ce">

Is it possible to add a command to move left/right between splits?

**Comment by mklement0** [comment]
`ttab` only ever submits a command that _creates_ terminal tabs / windows, then exits.

Thus, it has no control over what happens thereafter.

**Comment by mklement0** [comment]
I'm closing this, but let me know if I misinterpreted your issue.

**Comment by danielcompton** [comment]
I guess I was imagining there could be a new command that just sent an applescript command to move to the next window pane. Something like `ttab --right`, `ttab --down`.

**Comment by mklement0** [comment]
I see, @danielcompton, but I feel this is outside of `ttab`'s mandate.

**Comment by danielcompton** [comment]
Thanks! I think https://github.com/TomAnthony/itermocil or https://github.com/remi/teamocil might be what I need for this.
